/*
 * config.h
 *
 *  Created on: Apr 24, 2022
 *      Author: dante
 */

#ifndef CONFIG_H_
#define CONFIG_H_

#include "data.h"

#define VERBOSE 1

// Number of bytes used for storing segmentation blocks with 2 bits per block
#define SEGMENTATION_ARRAY_SIZE 361  // 38 * 38 / 4

// Number of bytes used for storing orientation for segmentation blocks with 1 byte per block
#define ORIENTATION_ARRAY_SIZE 1444

#define NORMALIZATION_DESIRED_MEAN     130
#define NORMALIZATION_DESIRED_VARIANCE 20000

#define CONTRAST_CONSTANT   2
#define CONTRAST_BLOCK_SIZE 11

#define BLOCK_ROW_SIZE 8
#define BLOCK_COL_SIZE 8

#define NO_BLOCKS_ROW 38  // ceil(MAX_IMAGE_LENGTH / BLOCK_ROW_SIZE)
#define NO_BLOCKS_COL 38  // ceil(MAX_IMAGE_WIDTH / BLOCK_COL_SIZE)

#define BLOCK_VARIANCE_THRESHOLD 120.0

#define BACKGROUND_BLOCK 0
#define FOREGROUND_BLOCK 1

#define EROSION_ITERATIONS                                2
#define BACKGROUND_EROSION_FOREGROUND_NEIGHBORS_THRESHOLD 4
#define FOREGROUND_EROSION_BACKGROUND_NEIGHBORS_THRESHOLD 3

#define TYPE_1_H_BLOCK 1
#define TYPE_2_V_BLOCK 2

#define TYPE_1_BLOCK_OUTPUT_INTENSITY 200
#define TYPE_2_BLOCK_OUTPUT_INTENSITY 70

#define TYPE_1_BLOCK_EROSION_TYPE_2_NEIGHBORS_THRESHOLD 6
#define TYPE_2_BLOCK_EROSION_TYPE_1_NEIGHBORS_THRESHOLD 6

#define RIDGE_INTENSITY      70
#define WEAK_RIDGE_INTENSITY 150
#define VALLEY_INTENSITY     210

#define THINNING_ITERATIONS                     2
#define THINNING_VALLEY_NEIGHBORS_MIN_THRESHOLD 3
#define THINNING_VALLEY_NEIGHBORS_MAX_THRESHOLD 7

#define ZS_THINNING_RIDGE_NEIGHBORS_MIN_THRESHOLD 2
#define ZS_THINNING_RIDGE_NEIGHBORS_MAX_THRESHOLD 6

#define ZS_THINNING_BLOCK_ROW_SIZE 32
#define ZS_THINNING_BLOCK_COL_SIZE 32

#endif /* CONFIG_H_ */
