#ifndef _FINGERPRINT_EXTRACTION_CONFIG_H
#define _FINGERPRINT_EXTRACTION_CONFIG_H

#define VERBOSE 1

#define BLOCK_ROW_SIZE 8
#define BLOCK_COL_SIZE 8

#define MAX_IMAGE_LENGTH 300
#define MAX_IMAGE_WIDTH  300

#define BLOCK_VARIANCE_THRESHOLD 60.0

#define FOREGROUND_BLOCK 1
#define BACKGROUND_BLOCK 0

#define EROSION_ITERATIONS                     2
#define EROSION_FOREGROUND_NEIGHBORS_THRESHOLD 4

#endif